version: "3"

services:
  data_access_server_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - app_network
    env_file:
      - path: ${PWD}/.env
    environment:
      - APP_CACHE_DATA:${APP_CACHE_DATA}
      - APP_CACHE_ITEM_MAX:${APP_CACHE_ITEM_MAX}
      - APP_S3_BUCKET:${APP_S3_BUCKET}
      - APP_LOG_LEVEL:${APP_LOG_LEVEL}
      - APP_PORT:${APP_PORT}
      - APP_LOCAL_ONLY:${APP_LOCAL_ONLY}
    expose:
      - ${APP_PORT}
    volumes:
      - ${APP_CACHE_DIR}:/app_data_cache
  
  data_access_server_proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      args:
        - NGINX_CONF=${APP_NGINX_CONF}
    networks:
      - app_network
    env_file:
      - path: ${PWD}/.env
    ports:
      - ${APP_PORT}:80

networks:
  app_network:
    name: app_services_network
    driver: 'bridge'